/* eslint-disable no-unused-vars */
export enum MedicalSpecialty {
  ALERGOLOGIA = "Allergology",
  ANESTESIOLOGIA = "Anesthesiology",
  ANGIOLOGIA = "Angiology",
  CANCEROLOGIA = "Cancerology",
  CARDIOLOGIA = "Cardiology",
  CIRURGIA_CARDIOVASCULAR = "Cardiovascular Surgery",
  CIRURGIA_CABECA_PESCOCO = "Head and Neck Surgery",
  CIRURGIA_DIGESTIVA = "Digestive Surgery",
  CIRURGIA_GERAL = "General Surgery",
  CIRURGIA_PEDIATRICA = "Pediatric Surgery",
  CIRURGIA_PLASTICA = "Plastic Surgery",
  CIRURGIA_TORACICA = "Thoracic Surgery",
  CIRURGIA_VASCULAR = "Vascular Surgery",
  CLINICA_MEDICA = "Internal Medicine",
  DERMATOLOGIA = "Dermatology",
  ENDOCRINOLOGIA = "Endocrinology and Metabolism",
  ENDOSCOPIA = "Endoscopy",
  GASTROENTEROLOGIA = "Gastroenterology",
  GERIATRIA = "Geriatrics",
  GINECOLOGIA_OBSTETRICIA = "Gynecology and Obstetrics",
  HEMATOLOGIA = "Hematology and Hemotherapy",
  HEPATOLOGIA = "Hepatology",
  HOMEOPATIA = "Homeopathy",
  INFECTOLOGIA = "Infectious Diseases",
  MASTOLOGIA = "Mastology",
  MEDICINA_DE_EMERGENCIA = "Emergency Medicine",
  MEDICINA_DO_ESPORTO = "Sports Medicine",
  MEDICINA_DO_TRABALHO = "Occupational Medicine",
  MEDICINA_DE_FAMILIA = "Family and Community Medicine",
  MEDICINA_FISICA_REABILITACAO = "Physical Medicine and Rehabilitation",
  MEDICINA_INTENSIVA = "Intensive Care Medicine",
  MEDICINA_LEGAL = "Legal Medicine and Medical Expertise",
  NEFROLOGIA = "Nephrology",
  NEUROCIRURGIA = "Neurosurgery",
  NEUROLOGIA = "Neurology",
  NUTROLOGIA = "Nutrology",
  OFTALMOLOGIA = "Ophthalmology",
  ONCOLOGIA_CLINICA = "Clinical Oncology",
  ORTOPEDIA_TRAUMATOLOGIA = "Orthopedics and Traumatology",
  OTORRINOLARINGOLOGIA = "Otorhinolaryngology",
  PATOLOGIA = "Pathology",
  PATOLOGIA_CLINICA = "Clinical Pathology / Laboratory Medicine",
  PEDIATRIA = "Pediatrics",
  PNEUMOLOGIA = "Pulmonology",
  PSIQUIATRIA = "Psychiatry",
  RADIOLOGIA = "Radiology and Diagnostic Imaging",
  RADIOTERAPIA = "Radiotherapy",
  REUMATOLOGIA = "Rheumatology",
  UROLOGIA = "Urology",
}

export const medicalSpecialties = Object.entries(MedicalSpecialty).map(
  ([key, value]) => ({
    value: MedicalSpecialty[key as keyof typeof MedicalSpecialty],
    label: value,
  }),
);
