/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Clic Flow API
 * API documentation for Clic Flow
 * OpenAPI spec version: 1.0
 */

export type CreatePatientDtoSex =
  (typeof CreatePatientDtoSex)[keyof typeof CreatePatientDtoSex];

export const CreatePatientDtoSex = {
  male: "male",
  female: "female",
} as const;
