/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Clic Flow API
 * API documentation for Clic Flow
 * OpenAPI spec version: 1.0
 */
import type { CreatePatientDtoSex } from "./createPatientDtoSex";

export interface CreatePatientDto {
  name: string;
  email: string;
  phoneNumber: string;
  sex: CreatePatientDtoSex;
  clinicId: string;
}
