/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Clic Flow API
 * API documentation for Clic Flow
 * OpenAPI spec version: 1.0
 */

export type DashboardControllerGetDailyAppointmentsDataParams = {
  clinicId: string;
  from: string;
  to: string;
};
