/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Clic Flow API
 * API documentation for Clic Flow
 * OpenAPI spec version: 1.0
 */

export * from "./appointmentControllerFindAllParams";
export * from "./appointmentDto";
export * from "./authControllerDeleteSessionParams";
export * from "./authControllerSessionParams";
export * from "./createAppointmentDto";
export * from "./createDoctorDto";
export * from "./createPatientDto";
export * from "./createPatientDtoSex";
export * from "./dashboardControllerGetDailyAppointmentsDataParams";
export * from "./dashboardControllerGetSummaryParams";
export * from "./dashboardControllerGetTodayAppointmentsParams";
export * from "./dashboardControllerGetTopDoctorsParams";
export * from "./dashboardControllerGetTopSpecialtiesParams";
export * from "./doctorControllerFindAllParams";
export * from "./doctorDto";
export * from "./loginDto";
export * from "./patientControllerFindAllParams";
export * from "./patientDto";
export * from "./patientDtoSex";
export * from "./registerDto";
export * from "./updatePatientDto";
