/**
 * Generated by orval v8.9.0 🍺
 * Do not edit manually.
 * Clic Flow API
 * API documentation for Clic Flow
 * OpenAPI spec version: 1.0
 */

export type PatientDtoSex = (typeof PatientDtoSex)[keyof typeof PatientDtoSex];

export const PatientDtoSex = {
  male: "male",
  female: "female",
} as const;
